HTSP/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from authentication.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('products/', include('products.urls')),
    path('order/', include('orders.urls')),
    path('reports/', include('reports.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product-list'),
    path('<int:pk>/detail/', views.ProductDetailView.as_view(), name='product-detail'),
    path('<int:pk>/add_to_order/', views.AddToOrderView.as_view(), name='add-to-order')
]

products/models.py
from django.db import models


class Product(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField(blank=True, null=True)
    country_producer = models.ForeignKey('Country', blank=True, null=True, on_delete=models.SET_NULL)
    type = models.ForeignKey('ProductType', null=True, on_delete=models.SET_NULL)
    price = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.name


class ProductType(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

products/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView
from django.views.generic.list import BaseListView, MultipleObjectTemplateResponseMixin

from orders.models import Order
from products.filters import ProductFilter
from products.models import Product


class ProductDetailView(LoginRequiredMixin, DetailView):
    """Get specific product"""
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'
    success_url = reverse_lazy('products:product-detail')

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, pk=self.kwargs['pk'])


class AddToOrderView(LoginRequiredMixin, View):
    """add to logic to add item to order"""
    def post(self, request, pk):
        order, _ = Order.objects.get_or_create(user=request.user, is_active=True)
        product = get_object_or_404(Product, id=pk)
        order_item, created = order.items.get_or_create(product=product)
        if not created:
            order_item.quantity += 1
            order_item.save()
            messages.info(request, f"Товарів у корзині {order_item.quantity}.")
        else:
            messages.info(request, "Товар додано в корзину.")
            pass
        return redirect("products:product-detail", pk)


class ProductListView(LoginRequiredMixin, MultipleObjectTemplateResponseMixin, BaseListView):
    """Get list of products"""
    model = Product
    filterset_class = ProductFilter
    template_name = 'products/product_list.html'
    success_url = reverse_lazy('products:product-list')

    def get_queryset(self):
        queryset = self.model.objects.filter(type__isnull=False)
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Pass the filterset to the template - it provides the form.
        context['filterset'] = self.filterset
        return context

templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-center m-5">
        <div>
            <img src="{{ product.image.url }}" width="470" height="370px" alt="">
        </div>
        <div>
            <b>Назва: </b>
            {{ product.name }}
        </div>
        <div>
            <b>Опис: </b>
            {{ product.description }}
        </div>
        <div>
            <b>Країна-виробник: </b>
            {{ product.country_producer }}
        </div>
        <div>
            <b>Тип: </b>
            {{ product.type }}
        </div>
        <div>
            <b>Ціна: </b>
            {{ product.price }} грн.
        </div>

        <form action="{% url 'products:add-to-order' product.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Додати до кошика">
        </form>

    </div>
{% endblock content %}

templates/products/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="content-center">
        <!-- Велосипеди -->
        <div class="main container-fluid padding">
            <form method="get">
                <input type="text" name="search" id="id_search" placeholder="Пошук" value="{{ filterset.form.search.value|default:'' }}">
                {{ filterset.form.ordering }}
                <input type="submit" />
            </form>
            <div class="block1" style="margin: 30px">
                {% for product in product_list %}
                    <div style="margin-left: 40px;margin-right: 40px">
                        <a href="{% url 'products:product-detail' product.id %}">
                            <img src="{{ product.image.url }}" width="470" height="370px" alt="">
                            <hr>
                            <h4>
                                {{ product.name }}
                            </h4>
                        </a>
                        <div>Тип: {{ product.type }}</div>
                        <div>Виробник: {{ product.country_producer.name }}</div>
                        <p>Ціна: {{ product.price }} грн.</p>
                        <hr>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- ./Велосипеди -->
    </div>
{% endblock content %}