HTSP/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from authentication.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('products/', include('products.urls')),
    path('order/', include('orders.urls')),
    path('reports/', include('reports.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from authentication import views

app_name = 'auth'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'order'

urlpatterns = [
    path('', views.OrderListView.as_view(), name='order-list'),
    path('<int:order_item_id>/remove_item/', views.RemoveOrderItemView.as_view(), name='remove-order-item'),
    path('order/', views.MakeOrderView.as_view(), name='make-order'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product-list'),
    path('<int:pk>/detail/', views.ProductDetailView.as_view(), name='product-detail'),
    path('<int:pk>/add_to_order/', views.AddToOrderView.as_view(), name='add-to-order')
]

reports/urls.py
from django.urls import path
from reports import views

app_name = 'reports'

urlpatterns = [
    path('', views.SalesReportView.as_view(), name='sales-report'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Мисливський магазин</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="Тарас Полевий">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/navbarstyle.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/firstpage.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/secondpage.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/thirdpage.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/fourthpage.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/footer.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/alerts.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>

    {% block links %}
    {% endblock links %}
</head>

<body>
    <!-- Панель керування -->
    <div class="header">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <div class="mr-auto"></div>
                    <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="{% url 'dashboard' %}">Головна</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:product-list' %}">Товари</a>
                        </li>
                        <li class="nav-item">
                            <b>
                                <a class="nav-link" id="velo" href="{% url 'order:order-list' %}">Кошик</a>
                            </b>
                        </li>
                        {% if user.is_staff %}
                            <li class="nav-item">
                                <b>
                                    <a style="color: lightgreen !important" class="nav-link" id="velo" href="{% url 'reports:sales-report' %}">Звіт продажів</a>
                                </b>
                            </li>
                        {% endif %}
                    </ul>
                    <div style="margin-right:1rem; display: flex">
                        {% if user.is_authenticated %}
                            <div style="margin-right: 20px">{{ user.username }}</div>
                            <a href="{% url 'auth:logout' %}">Logout</a>
                        {% else %}
                            <a href="{% url 'auth:login' %}">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <!-- ./Панель керування -->

    <!-- Контент -->
    <div style="min-height: 300px" id="content">
        <div>
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
        {% endif %}
        </div>

        {% block content %}
        {% endblock content %}
    </div>
    <!-- ./Контент -->

    <!-- Footer -->
    <section id="footer">
        <div class="container">
            <div class="row mt-2">
                <hr>
                <div class="text-center text-white">
                    <p>
                        Виконав студент групи КН-311 Полевий Т.А.
                    </p>
                </div>
                <hr>
            </div>
        </div>
    </section>
    <!-- ./Footer -->


    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block scripts %}
    {% endblock scripts %}
</body>

</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div>
        You are logged in!
    </div>
{% endblock content %}