HTSP/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from authentication.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('products/', include('products.urls')),
    path('order/', include('orders.urls')),
    path('reports/', include('reports.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders import views

app_name = 'order'

urlpatterns = [
    path('', views.OrderListView.as_view(), name='order-list'),
    path('<int:order_item_id>/remove_item/', views.RemoveOrderItemView.as_view(), name='remove-order-item'),
    path('order/', views.MakeOrderView.as_view(), name='make-order'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product-list'),
    path('<int:pk>/detail/', views.ProductDetailView.as_view(), name='product-detail'),
    path('<int:pk>/add_to_order/', views.AddToOrderView.as_view(), name='add-to-order')
]

orders/models.py
from django.db import models

from authentication.models import User
from products.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateField(null=True)

    def __str__(self):
        return f'{self.id}'

    @property
    def total_price(self):
        return sum([item.item_price for item in self.items.all()])


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    @property
    def item_price(self):
        return self.quantity * self.product.price

orders/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic.list import BaseListView, MultipleObjectTemplateResponseMixin

from orders.models import Order, OrderItem


class RemoveOrderItemView(LoginRequiredMixin, View):
    def post(self, request, order_item_id):
        order, _ = Order.objects.get_or_create(user=request.user, is_active=True)
        order_item = get_object_or_404(OrderItem, id=order_item_id, order=order)
        order_item.delete()
        messages.info(request, "Товар вилучено з кошика.")
        return redirect("order:order-list")


class OrderListView(LoginRequiredMixin, MultipleObjectTemplateResponseMixin, BaseListView):
    model = OrderItem
    template_name = 'orders/order_list.html'
    success_url = reverse_lazy('order:order-list')

    def get_queryset(self):
        order, _ = Order.objects.get_or_create(user=self.request.user, is_active=True)
        return self.model.objects.filter(order=order.pk)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(OrderListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['order'] = Order.objects.get(user=self.request.user, is_active=True)
        return context


class MakeOrderView(LoginRequiredMixin, View):
    def post(self, request):
        order, _ = Order.objects.get_or_create(user=request.user, is_active=True)
        if not order.items.all():
            messages.info(request, "Ваша корзина пуста.")
            return redirect("order:order-list")
        order.is_active = False
        order.order_date = timezone.now()
        order.save()

        Order.objects.create(user=request.user, is_active=True)
        messages.success(request, f"Ви успішно оформили замовлення на суму {order.total_price} грн.")
        return redirect("order:order-list")

templates/orders/order_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="">
        <div class="main container-fluid padding">
            {% for order_item in orderitem_list %}
                <div class="block1 row">
                    <a href="{% url 'products:product-detail' order_item.product.pk %}">
                        <h4>
                            {{ order_item.product.name }}
                        </h4>
                    </a>
                    <p>Кількість: {{ order_item.quantity }} шт.</p>
                    <p>Ціна: {{ order_item.product.price }} грн.</p>
                    <p>Сумарно: {{ order_item.item_price }} грн.</p>

                    <form action="{% url 'order:remove-order-item' order_item.pk %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Вилучити з кошика">
                    </form>
                </div>
            {% endfor %}
            <div>
                <p>Разом: {{ order.total_price }} грн.</p>
                <form action="{% url 'order:make-order' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Замовити">
                </form>
            </div>
        </div>
    </div>
{% endblock content %}